<a href="https://colab.research.google.com/github/Mariusz-Bienasz/Python_project_7/blob/main/Lab7b_Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programowanie w Python
Autor dr Aneta Polewko-Klim

## Pandas wstęp
Homepage -http://pandas.pydata.org/  
DataCamp web https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python

**Additional tutorials**

http://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/

### Import niezbędnych bibliotek

In [1]:
#!pip install pandas

In [2]:
import pandas as pd  # biblioteka do obsługi danych w formie tabelarycznej/ramek danych
import numpy as np   # biblioteka do obsługi danych w macierzy, wektorów, tablic
import os  # biblioteka do obsługi plików i folderów

In [3]:
from google.colab import drive
drive.mount('/content/drive')    # podłączenie zasobów z dysku Google

Mounted at /content/drive

In [4]:
import os
import pandas as pd
folder_path = '/content/drive/MyDrive/Colab Notebooks/dataset/'
data = pd.read_excel(os.path.join(folder_path, 'titanic_train.xlsx'))
data.shape

(891, 12)

###  Tworzenie tabel/ramek danych

In [6]:
dr = pd.date_range('1/6/2019', periods=6)  # wektor/kolumna, generowanie wektora z dat, przedział = liczba miesięcy
dr

DatetimeIndex(['2019-01-06', '2019-01-07', '2019-01-08', '2019-01-09',
               '2019-01-10', '2019-01-11'],
              dtype='datetime64[ns]', freq='D')

In [7]:
s = pd.Series(np.random.randn(5), index=['A', 'B', 'C', 'D', 'E'])  # kolumna + nazwy wierszy (wartości są losowane)
s

A   -1.332298
B   -0.410524
C    0.160576
D    1.206745
E    1.623471
dtype: float64

In [8]:
# tworzymy ramkę danych z losowymi liczbami 6x3, nazwy wierszy (id wierszy) to wartości dr, zwróć uwagę na rozmiary
tabela1 = zawartosc = np.random.randn(6, 3)
df = pd.DataFrame(tabela1, index=dr, columns=['A', 'B', 'C'])
df

                   A         B         C
2019-01-06 -0.168446 -0.140465  1.665896
2019-01-07  1.821575  0.769471 -0.869706
2019-01-08  0.856160 -0.125949 -1.397612
2019-01-09 -1.057904 -1.011926 -2.197632
2019-01-10 -0.536949 -0.737840  1.236573
2019-01-11  1.153002 -0.353787  0.726092

In [9]:

# tworzenie wielowymiarowych ramek danych tu "kostka 3D o wymiarach 2x5x4"

import xarray as xr
ds = xr.Dataset({"foo": (("x", "y"), np.random.randn(2, 3))},
                coords={
                    "x": [10, 20],
                    "y": ["a", "b", "c"],
                    "along_x": ("x", np.random.randn(2)),
                    "scalar": 123,
},)

df = ds.to_dataframe()
df
# print(pd.__version__)
# print(np.__version__)

           foo   along_x  scalar
x  y
10 a  0.473250  1.200468     123
   b  0.696446  1.200468     123
   c -1.855969  1.200468     123
20 a -1.674943  0.139563     123
   b  0.203217  0.139563     123
   c -1.663481  0.139563     123

### Tworzymy przykładową ramkę danych wykorzystując słownik

In [10]:
dictionary = {'one':[1,10,100,1000,10000],
     'two':[2,20,200,2000,2000],
     'price':['prod1','prod3','prod2','prod1','prod2']}  # wykorzystamy słownik do utworzenia odpowiedniej struktury
dictionary

{'one': [1, 10, 100, 1000, 10000],
 'two': [2, 20, 200, 2000, 2000],
 'price': ['prod1', 'prod3', 'prod2', 'prod1', 'prod2']}

In [11]:
dfs = pd.DataFrame(dictionary)
dfs

     one   two  price
0      1     2  prod1
1     10    20  prod3
2    100   200  prod2
3   1000  2000  prod1
4  10000  2000  prod2

In [12]:
type(dfs)  # informacje o utworzonym obiekcie

pandas.core.frame.DataFrame

In [13]:
dfs.head(2)  # wypisuje 2 pierwsze wiersze tabeli

   one  two  price
0    1    2  prod1
1   10   20  prod3

In [14]:
dfs.tail(3)  # pokazuje 3 końcowe wiersze tabeli

     one   two  price
2    100   200  prod2
3   1000  2000  prod1
4  10000  2000  prod2

In [15]:
dfs.info() # podstawowe informacje o danych

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   one     5 non-null      int64
 1   two     5 non-null      int64
 2   price   5 non-null      object
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [16]:
dfs.shape  # liczba wierszy i liczba kolumn

(5, 3)

In [17]:
dfs.columns # wyswietla nazwy kolumn tabeli

Index(['one', 'two', 'price'], dtype='object')

In [18]:
dfs['price'].value_counts()  # zliczamy ilość elementów o tych samych wartościach z kolumny 'price'

price
prod1    2
prod2    2
prod3    1
Name: count, dtype: int64

In [19]:
z = dfs['price'] # zawartość kolumny z nagłówkiem price
z
#z.value_counts()

0    prod1
1    prod3
2    prod2
3    prod1
4    prod2
Name: price, dtype: object

In [20]:
dfs[['price', 'one']] # ograniczenie zbioru do wybranych nazw kolumn 'price', 'one' z tabeli

   price    one
0  prod1      1
1  prod3     10
2  prod2    100
3  prod1   1000
4  prod2  10000

In [21]:
dfs[0:3] # selekcja wybranych wierszy tabeli data np: 0,1,2

   one  two  price
0    1    2  prod1
1   10   20  prod3
2  100  200  prod2

## Metoda: groupby
##### metoda grupuje dane tabelaryczne względem kolumny, na wyodrębnionych w ten sposób podgrupach/podzbiorach wykonuje rónocześnie zadeklarowaną operację

In [22]:
dfPrice = dfs.groupby('price')  # grupujemy dane po kolumnie z nagłówkiem 'price'

In [23]:
dfPrice.ngroups  # sprawdzenie liczby utworzonych podzbiorów <=> liczba kategorii w kolumnie 'price'

3

In [24]:
dfPrice.groups  # podstawowe informacje o typach danych wewnątrz ramki danych

{'prod1': [0, 3], 'prod2': [2, 4], 'prod3': [1]}

In [25]:
dfPrice.get_group('prod1') # wydzielenie podzbioru danych 'prod1'

    one   two  price
0     1     2  prod1
3  1000  2000  prod1

In [26]:
dfPrice.describe()  # tabela podstawowych metryk statystyccznych zebranych dla poszczególnych podzbiorów z kolumny price

        one                                                                 \
      count    mean          std    min      25%     50%      75%      max
price
prod1   2.0   500.5   706.399674    1.0   250.75   500.5   750.25   1000.0
prod2   2.0  5050.0  7000.357134  100.0  2575.00  5050.0  7525.00  10000.0
prod3   1.0    10.0          NaN   10.0    10.00    10.0    10.00     10.0

        two
      count    mean          std    min    25%     50%     75%     max
price
prod1   2.0  1001.0  1412.799349    2.0  501.5  1001.0  1500.5  2000.0
prod2   2.0  1100.0  1272.792206  200.0  650.0  1100.0  1550.0  2000.0
prod3   1.0    20.0          NaN   20.0   20.0    20.0    20.0    20.0

In [27]:
dfPrice.sum()   # sumowanie wartości obiektów po kolumnach dla poszczególnych podzbiorów

         one   two
price
prod1   1001  2002
prod2  10100  2200
prod3     10    20

In [28]:
dfPrice.mean()  # srednia z kolumn

          one     two
price
prod1   500.5  1001.0
prod2  5050.0  1100.0
prod3    10.0    20.0

### Przykłady grupowania danych po wielu kolumnach

In [29]:
grouped = dfs.groupby(['price', 'one'])

In [30]:
print(grouped.get_group)

<bound method BaseGroupBy.get_group of <pandas.core.groupby.generic.DataFrameGroupBy object at 0x7ef6216dacf0>>

In [31]:
print(grouped.sum())

              two
price one
prod1 1         2
      1000   2000
prod2 100     200
      10000  2000
prod3 10       20

In [32]:
print(grouped.sum().index)

MultiIndex([('prod1',     1),
            ('prod1',  1000),
            ('prod2',   100),
            ('prod2', 10000),
            ('prod3',    10)],
           names=['price', 'one'])

### Praca na danych z pliku: zapis danych do pliku


The pandas I/O API is a set of top level reader functions accessed like pd.read_csv() that generally return a pandas object.

* read_csv
* read_excel
* read_hdf
* read_sql
* read_json
* read_msgpack (experimental)
* read_html
* read_gbq (experimental)
* read_stata
* read_sas
* read_clipboard
* read_pickle
The corresponding writer functions are object methods that are accessed like df.to_csv()

* to_csv
* to_excel
* to_hdf
* to_sql
* to_json
* to_msgpack (experimental)
* to_html
* to_gbq (experimental)
* to_stata
* to_clipboard
* to_pickle###  Praca na danych z pliku: odczyt danych z pliku

Sposób 1: wczytanie danych jeśli pracujesz z danymi na dysku google

In [33]:
from google.colab import drive
drive.mount('/content/drive')    # podłączenie zasobów z dysku Google

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [34]:
import os
import pandas as pd
folder_path = '/content/drive/MyDrive/Colab Notebooks/dataset/'
data = pd.read_excel(os.path.join(folder_path, 'titanic_train.xlsx'))
data.shape

(891, 12)

Sposób 2: wczytanie danych jeśli pracujesz lokalnie

In [36]:
#os.path.join(folder_path, 'titanic_train.xlsx')
#e:/DYDAKTYKA/Python/laboratorium/titanic_train.xlsx

#data = pd.read_excel('titanic_train.xlsx')  # tak wczytujemy dane z pliku jeśli jest w folderze roboczym
#data = pd.read_csv( 'movies.csv')

In [37]:
data.head()  # metoda .head wyświetla dla wszystkich kolumn 5 pierwszych wierszy

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Praca na danych z pliku: zapis danych do pliku

In [38]:
############# składnia funkcji dla plików z rozszerzeniem *.csv
# data.to_csv(path_or_buf=None, sep=',', na_rep='', float_format=None, columns=None,
#            header=True, index=True, index_label=None, mode='w', encoding=None,
#            compression=None, quoting=None, quotechar='"', line_terminator='\n',
#            chunksize=None, tupleize_cols=False, date_format=None, doublequote=True,
#            escapechar=None, decimal='.', **kwds)

In [39]:
############## składnia funkcji dla plików z rozszerzeniem *.xlsx
# data.to_excel(excel_writer, sheet_name='Sheet1', na_rep='', float_format=None, columns=None,
#              header=True, index=True, index_label=None, startrow=0, startcol=0, engine=None,
#              merge_cells=True, encoding=None, inf_rep='inf', verbose=True)

In [40]:
dataTitanic = data
folder_path = ''
data.to_excel(os.path.join(folder_path, 'titanic_copy.xlsx')) # zapis do pliku *.xlsx
data.to_csv(os.path.join(folder_path, 'titanic_copy.csv'), index=False)    # zapis do pliku *.csv

### Zadanie 1
#### Wykorzystując dane z pliku titanic.csv:
#### a) wypisz: pierwsze 3 kolumny, wiersze od 4 do 9,
#### b) wyznacz średnią wieku pasażerów statku
#### c) określ ile osób przeżyło katastrofę statku
#### d) określ statystyki podstawowe dla 2 grup/klas: male i female
#### e) ilu pasażerów podróżowało klasą 1 ilu 3

In [54]:
folder_path = '/content/drive/MyDrive/Colab Notebooks/dataset/'
data = pd.read_csv(os.path.join(folder_path, 'titanic_train.csv'))

print(data.iloc[3:9, 0:3])
print('--------------------')
print(round(data['Age'].mean()),2)
print('--------------------')
print(data.Survived.sum())
print('--------------------')
print(data.groupby('Sex').describe())
print('--------------------')
print(data.Pclass.value_counts())

   PassengerId  Survived  Pclass
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
--------------------
30 2
--------------------
342
--------------------
       PassengerId                                                             \
             count        mean         std  min     25%    50%     75%    max
Sex
female       314.0  431.028662  256.846324  2.0  231.75  414.5  641.25  889.0
male         577.0  454.147314  257.486139  1.0  222.00  464.0  680.00  891.0

       Survived            ... Parch        Fare                              \
          count      mean  ...   75%  max  count       mean        std   min
Sex                        ...
female    314.0  0.742038  ...   1.0  6.0  314.0  44.479818  57.997698  6.75
male      577.0  0.188908  ...   0.0  5.0  577.0  25.523893  43.138263  0.00


              25%   50%    75%       max
Sex
female  12.071875  23.0  55.00  512.3292
male     7.895800  10.5  26.55  512.3292

[2 rows x 56 columns]
--------------------
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

## Metody .loc i .iloc - służą do selekcji danych
#### składnia:  nazwaObiektu.loc[numbersRows, nameColumns]      oraz   nazwaObiektu.iloc[numbersRows, numbersColumns]

#### Zadanie 2 Zapoznaj się z przykładami działania metod .loc oraz .iloc

In [58]:
print(data.loc[5])  # wyświetl dane 6 wiersz i wszystkie kolumny
print(data.loc[5:10]) # wyświetl 6,...,9 wiersze i wszystkie kolumny
print(data.loc[5, 'Name']) # wyświetl 6 wiersz z kolumny 'Name'
print(data.loc[5:10, 'Name'])  # wyświetl 6,...,9 wiersze z kolumny 'Name'
print(data.columns)
print(data.loc[5:10, :'Pclass']) # wyświetl 6,...,10 wiersze i wszystkie kolumny poprzedzające kolumne 'Pclass'
print(data.loc[5:10, ['Name', 'Pclass', 'Survived']]) # wyświetl 6,...,10 wiersze i kolumny 'Name', 'Pclass', 'Survived'

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object
    PassengerId  Survived  Pclass  \
5             6         0       3
6             7         0       1
7             8         0       3
8             9         1       3
9            10         1       2
10           11         1       3

                                                 Name     Sex   Age  SibSp  \
5                                    Moran, Mr. James    male   NaN      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master. Gosta Leonard    male   2.0      3
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1

    Parch   Ticket     Fare Cabin Embarked
5       0   330877   8.4583   NaN        Q
6       0    17463  51.8625   E46        S
7       1   349909  21.0750   NaN        S
8       2   347742  11.1333   NaN        S
9       0   237736  30.0708   NaN        C
10      1  PP 9549  16.7000    G6        S
Moran, Mr. James
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
Name: Name, dtype: object
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
    PassengerId  Survived  Pclass
5             6         0       3
6             7         0       1
7             8         0       3
8             9         1       3
9            10         1       2
10           11         1       3
                                                 Name  Pclass  Survived
5                                    Moran, Mr. James       3         0
6                             McCarthy, Mr. Timothy J       1         0
7                      Palsson, Master. Gosta Leonard       3         0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       3         1
9                 Nasser, Mrs. Nicholas (Adele Achem)       2         1
10                    Sandstrom, Miss. Marguerite Rut       3         1

In [59]:
print(data.loc[5])  # wyświetl dane 6 wiersz i wszystkie kolumny
print(data.loc[5:10]) # wyświetl 6,...,9 wiersze i wszystkie kolumny
print(data.loc[5, 'Name']) # wyświetl 6 wiersz z kolumny 'Name'
print(data.loc[5:10, 'Name'])  # wyświetl 6,...,9 wiersze z kolumny 'Name'
print(data.columns)
print(data.loc[5:10, :'Pclass']) # wyświetl 6,...,10 wiersze i wszystkie kolumny poprzedzające kolumne 'Pclass'
print(data.loc[5:10, ['Name', 'Pclass', 'Survived']]) # wyświetl 6,...,10 wiersze i kolumny 'Name', 'Pclass', 'Survived'

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object
    PassengerId  Survived  Pclass  \
5             6         0       3
6             7         0       1
7             8         0       3
8             9         1       3
9            10         1       2
10           11         1       3

                                                 Name     Sex   Age  SibSp  \
5                                    Moran, Mr. James    male   NaN      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master. Gosta Leonard    male   2.0      3
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1

    Parch   Ticket     Fare Cabin Embarked
5       0   330877   8.4583   NaN        Q
6       0    17463  51.8625   E46        S
7       1   349909  21.0750   NaN        S
8       2   347742  11.1333   NaN        S
9       0   237736  30.0708   NaN        C
10      1  PP 9549  16.7000    G6        S
Moran, Mr. James
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
Name: Name, dtype: object
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
    PassengerId  Survived  Pclass
5             6         0       3
6             7         0       1
7             8         0       3
8             9         1       3
9            10         1       2
10           11         1       3
                                                 Name  Pclass  Survived
5                                    Moran, Mr. James       3         0
6                             McCarthy, Mr. Timothy J       1         0
7                      Palsson, Master. Gosta Leonard       3         0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       3         1
9                 Nasser, Mrs. Nicholas (Adele Achem)       2         1
10                    Sandstrom, Miss. Marguerite Rut       3         1

In [60]:
print(data.iloc[1])
print(data.iloc[5:10])
print(data.iloc[5, 3])  # dane: 5 wiersz 3 kolumna
print(data.iloc[5:10, 3])
print(data.iloc[5:10, :3])
print(data.iloc[range(0, 50, 5), [1, 3]]) # dane: wiersze od 0 do 50 z krokiem 5, kolumny: 1, 3
print(data.iloc[:50:5, [1, 3]]) # analog do formuły powyżej
print(data.iloc[-10:]) # minus oznacza liczenie od końca tu wyświetl od 10 wiersza od końca
print(data.Pclass.max()) # Wartość max i min dla kolumny Pclass
print(data.Pclass.min())
print(data.Pclass.sum()) # Wartość sumy dla kolumny Pclass
print(data['Cabin'])
print(data.Cabin.fillna(0)) # wstaw 0 w rekordy w których brakuje danych czyli jest NaN w kolumnie Cabin

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object
   PassengerId  Survived  Pclass  \
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                     Palsson, Master. Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch  Ticket     Fare Cabin Embarked
5      0  330877   8.4583   NaN        Q
6      0   17463  51.8625   E46        S
7      1  349909  21.0750   NaN        S
8      2  347742  11.1333   NaN        S
9      0  237736  30.0708   NaN        C
Moran, Mr. James
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object
   PassengerId  Survived  Pclass
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2
    Survived                                               Name
0          0                            Braund, Mr. Owen Harris
5          0                                   Moran, Mr. James
10         1                    Sandstrom, Miss. Marguerite Rut
15         1                   Hewlett, Mrs. (Mary D Kingcome)
20         0                               Fynney, Mr. Joseph J
25         1  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
30         0                           Uruchurtu, Don. Manuel E
35         0                     Holverson, Mr. Alexander Oskar
40         0     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
45         0                           Rogers, Mr. William John
    Survived                                               Name
0          0                            Braund, Mr. Owen Harris
5          0                                   Moran, Mr. James
10         1                    Sandstrom, Miss. Marguerite Rut
15         1                   Hewlett, Mrs. (Mary D Kingcome)
20         0                               Fynney, Mr. Joseph J
25         1  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
30         0                           Uruchurtu, Don. Manuel E
35         0                     Holverson, Mr. Alexander Oskar
40         0     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
45         0                           Rogers, Mr. William John
     PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann
882          883         0       3              Dahlberg, Miss. Gerda Ulrika
883          884         0       2             Banfield, Mr. Frederick James
884          885         0       3                    Sutehall, Mr. Henry Jr
885          886         0       3      Rice, Mrs. William (Margaret Norton)
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
881    male  33.0      0      0            349257   7.8958   NaN        S
882  female  22.0      0      0              7552  10.5167   NaN        S
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
885  female  39.0      0      5            382652  29.1250   NaN        Q
886    male  27.0      0      0            211536  13.0000   NaN        S
887  female  19.0      0      0            112053  30.0000   B42        S
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S
889    male  26.0      0      0            111369  30.0000  C148        C
890    male  32.0      0      0            370376   7.7500   NaN        Q
3
1
2057
0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object
0         0
1       C85
2         0
3      C123
4         0
       ...
886       0
887     B42
888       0
889    C148
890       0
Name: Cabin, Length: 891, dtype: object

#### Zadanie 3
#### Korzystając z danych z pliku titanic:
#### a) Podaj wiek najmłodszego pasażera statku
#### b) imputacja danych: podstaw wartość średnią za NaN w kolumnie Age
#### c) wyświetl wiersze 2,4,30 i tylko 3 kolumny Age Name Sex

In [63]:
folder_path = '/content/drive/MyDrive/Colab Notebooks/dataset/'
data = pd.read_csv(os.path.join(folder_path, 'titanic_train.csv'))

print(data.Age.min())

age = data.Age.mean()
data.Age = data.Age.fillna(age)

print(data.loc[[2, 4, 30], ['Age', 'Name', 'Sex']])

0.42
     Age                      Name     Sex
2   26.0    Heikkinen, Miss. Laina  female
4   35.0  Allen, Mr. William Henry    male
30  40.0  Uruchurtu, Don. Manuel E    male

#### Zadanie 4  Zapoznaj się z warunkową selekcją zmiennych

In [64]:
print(data['Pclass'] == 3) # określa które rekordy/wiersze kolumny Pclass mają bilet klasy 3
print(data.loc[data['Pclass'] == 3]) # wyświetla tylko te wiersze dla których w kolumnie Pclass jest bilet klasy 3
print(data[data['Pclass'] == 3]) # analog powyższej formuły
print(data[data['Cabin'].isin(['C85', 'C123'])])  # szukanie w kolumnie 'Cabin' konkretnych elementów/wartości tj.'C85', 'C123'
print(data[(data['Cabin'] == 'C123') & (data['Pclass']==1)]) # wiele warunków równocześnie  & => odpowiednik and

print(data[(data['Pclass'] == 1) & (data['Sex'] == 'female')].shape)
print(data['Pclass'] == 1)

0       True
1      False
2       True
3      False
4       True
       ...
886    False
887    False
888     True
889    False
890     True
Name: Pclass, Length: 891, dtype: bool
     PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris
2              3         1       3                    Heikkinen, Miss. Laina
4              5         0       3                  Allen, Mr. William Henry
5              6         0       3                          Moran, Mr. James
7              8         0       3            Palsson, Master. Gosta Leonard
..           ...       ...     ...                                       ...
882          883         0       3              Dahlberg, Miss. Gerda Ulrika
884          885         0       3                    Sutehall, Mr. Henry Jr
885          886         0       3      Rice, Mrs. William (Margaret Norton)
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
890          891         0       3                       Dooley, Mr. Patrick

        Sex        Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0      male  22.000000      1      0         A/5 21171   7.2500   NaN        S
2    female  26.000000      0      0  STON/O2. 3101282   7.9250   NaN        S
4      male  35.000000      0      0            373450   8.0500   NaN        S
5      male  29.699118      0      0            330877   8.4583   NaN        Q
7      male   2.000000      3      1            349909  21.0750   NaN        S
..      ...        ...    ...    ...               ...      ...   ...      ...
882  female  22.000000      0      0              7552  10.5167   NaN        S
884    male  25.000000      0      0   SOTON/OQ 392076   7.0500   NaN        S
885  female  39.000000      0      5            382652  29.1250   NaN        Q
888  female  29.699118      1      2        W./C. 6607  23.4500   NaN        S
890    male  32.000000      0      0            370376   7.7500   NaN        Q

[491 rows x 12 columns]
     PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris
2              3         1       3                    Heikkinen, Miss. Laina
4              5         0       3                  Allen, Mr. William Henry
5              6         0       3                          Moran, Mr. James
7              8         0       3            Palsson, Master. Gosta Leonard
..           ...       ...     ...                                       ...
882          883         0       3              Dahlberg, Miss. Gerda Ulrika
884          885         0       3                    Sutehall, Mr. Henry Jr
885          886         0       3      Rice, Mrs. William (Margaret Norton)
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
890          891         0       3                       Dooley, Mr. Patrick

        Sex        Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0      male  22.000000      1      0         A/5 21171   7.2500   NaN        S
2    female  26.000000      0      0  STON/O2. 3101282   7.9250   NaN        S
4      male  35.000000      0      0            373450   8.0500   NaN        S
5      male  29.699118      0      0            330877   8.4583   NaN        Q
7      male   2.000000      3      1            349909  21.0750   NaN        S
..      ...        ...    ...    ...               ...      ...   ...      ...
882  female  22.000000      0      0              7552  10.5167   NaN        S
884    male  25.000000      0      0   SOTON/OQ 392076   7.0500   NaN        S
885  female  39.000000      0      5            382652  29.1250   NaN        Q
888  female  29.699118      1      2        W./C. 6607  23.4500   NaN        S
890    male  32.000000      0      0            370376   7.7500   NaN        Q

[491 rows x 12 columns]
     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
137          138         0       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
137                        Futrelle, Mr. Jacques Heath    male  37.0      1

     Parch    Ticket     Fare Cabin Embarked
1        0  PC 17599  71.2833   C85        C
3        0    113803  53.1000  C123        S
137      0    113803  53.1000  C123        S
     PassengerId  Survived  Pclass  \
3              4         1       1
137          138         0       1

                                             Name     Sex   Age  SibSp  Parch  \
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0
137                   Futrelle, Mr. Jacques Heath    male  37.0      1      0

     Ticket  Fare Cabin Embarked
3    113803  53.1  C123        S
137  113803  53.1  C123        S
(94, 12)
0      False
1       True
2      False
3       True
4      False
       ...
886    False
887     True
888    False
889     True
890    False
Name: Pclass, Length: 891, dtype: bool

In [65]:
print(data)
print(data.columns)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000
2                               Heikkinen, Miss. Laina  female  26.000000
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000
4                             Allen, Mr. William Henry    male  35.000000
..                                                 ...     ...        ...
886                              Montvila, Rev. Juozas    male  27.000000
887                       Graham, Miss. Margaret Edith  female  19.000000
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118
889                              Behr, Mr. Karl Howell    male  26.000000
890                                Dooley, Mr. Patrick    male  32.000000

     SibSp  Parch            Ticket     Fare Cabin Embarked
0        1      0         A/5 21171   7.2500   NaN        S
1        1      0          PC 17599  71.2833   C85        C
2        0      0  STON/O2. 3101282   7.9250   NaN        S
3        1      0            113803  53.1000  C123        S
4        0      0            373450   8.0500   NaN        S
..     ...    ...               ...      ...   ...      ...
886      0      0            211536  13.0000   NaN        S
887      0      0            112053  30.0000   B42        S
888      1      2        W./C. 6607  23.4500   NaN        S
889      0      0            111369  30.0000  C148        C
890      0      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [66]:
print(data[data['Pclass'] == 1].shape)

(216, 12)

In [67]:
from pandas.core.groupby.groupby import get_groupby
from numpy.core.fromnumeric import shape
from pandas.core.groupby.groupby import get_groupby
from pandas.core.groupby import groupby

dane_sel = data.groupby(['Sex'])
dane_sel.describe()
data_female = dane_sel.get_group('female')

data_female.shape

/tmp/ipykernel_2967/1074449362.py:2: DeprecationWarning: numpy.core.fromnumeric is deprecated and has been renamed to numpy._core.fromnumeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.fromnumeric.shape.
  from numpy.core.fromnumeric import shape
/tmp/ipykernel_2967/1074449362.py:8: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  data_female = dane_sel.get_group('female')

(314, 12)

#### Zadanie 5
#### a) wyswietl dane pasażerów którzy mają wiek poniżej 25 lat i bilet klasy 2 zapisz uzyskane do pliku na dysk
#### b) wyświetl ile osób podróżowało statkiem, podaj w/w dane z podziałem na kategorie np.: płeć, klasa biletu, wiek (grupy co 10 lat)
#### c) określ ile osób przeżyło katastrofę statku

In [81]:
folder_path = '/content/drive/MyDrive/Colab Notebooks/dataset/'
data = pd.read_csv(os.path.join(folder_path, 'titanic_train.csv'))

d = (data['Age'] < 25) & (data['Pclass'] == 2)
print(d.head())
d.to_csv('Task5.csv', index=False)
print('----------------')
print(len(data))
print(data.Sex.value_counts())
print(data.Pclass.value_counts())
bins = range(0, 100, 10)
print((pd.cut(data.Age, bins = bins)).sort_index())
print('----------------')
print(data.Survived.sum())

0    False
1    False
2    False
3    False
4    False
dtype: bool
----------------
891
Sex
male      577
female    314
Name: count, dtype: int64
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
0      (20.0, 30.0]
1      (30.0, 40.0]
2      (20.0, 30.0]
3      (30.0, 40.0]
4      (30.0, 40.0]
           ...
886    (20.0, 30.0]
887    (10.0, 20.0]
888             NaN
889    (20.0, 30.0]
890    (30.0, 40.0]
Name: Age, Length: 891, dtype: category
Categories (9, interval[int64, right]): [(0, 10] < (10, 20] < (20, 30] < (30, 40] ... (50, 60] <
                                         (60, 70] < (70, 80] < (80, 90]]
----------------
342

#### Zadanie 6
#### Korzystając z daneych o filmach movies.csv
#### a) określ ile filmów nakręcono w każdym roku
#### b) określ który film miał najwięcej lajków na facebook-u
#### c) podziel zbiór ze względu na kategorię country lub color i określ dla każdej kategorii liczbę filmów o budżecie > 240mln
#### d) jaki film wykonany w kolorze miał największy budżet?
#### e) Czy w zbiorze znajdują się dane dla filmu Piraci z karaibów? Jeśli tak to ile kosztował ten film i kto był jego reżyserem
#### f) Jaki film miał największy budżet

In [106]:
data2 = pd.read_csv(os.path.join(folder_path, 'movies.csv'))
data2.head()

print(data2.title_year.value_counts().sort_index())
print('----------------')
id = data2.movie_facebook_likes.idxmax()
print(data2.loc[id, 'movie_title'])
print('----------------')
x = data2[data2.budget > 240000000]
print(x.groupby('color').count())
print('----------------')
y = data2[data2.color == 'Color']
idY = y.budget.idxmax()
print(y.loc[idY, 'movie_title'])
print('----------------')
p = data2[data2['movie_title'].str.contains('Pirates of the Caribbean', case=False, na=False)]
if not p.empty:
  for index, row in p.iterrows():
        title = row['movie_title'].strip()
        director = row['director_name']
        budgetn = row['budget']
        print(f" - Tytuł: {title}, Reżyser: {director}, Budżet: {budgetn}")
else:
    print("Nie znaleziono filmów o tym tytule w bazie.")
print('----------------')
idB = data2.budget.idxmax()
print(data2.loc[idB, 'movie_title'])

title_year
1916.0      1
1920.0      1
1925.0      1
1927.0      1
1929.0      2
         ...
2012.0    221
2013.0    237
2014.0    252
2015.0    226
2016.0    106
Name: count, Length: 91, dtype: int64
----------------
Interstellar
----------------
       movie_title  title_year  budget  gross  genres  language  country  \
color
Color           27          27      27     27      27        27       27

       movie_facebook_likes  imdb_score  num_voted_users  ...  \
color                                                     ...
Color                    27          27               27  ...

       actor_2_facebook_likes  actor_3_name  actor_3_facebook_likes  \
color
Color                      27            27                      27

       cast_total_facebook_likes  duration  plot_keywords  content_rating  \
color
Color                         27        27             27              26

       aspect_ratio  facenumber_in_poster  movie_imdb_link
color
Color            26                    27               27

[1 rows x 27 columns]
----------------
The Host
----------------
 - Tytuł: Pirates of the Caribbean: At World's End, Reżyser: Gore Verbinski, Budżet: 300000000.0
 - Tytuł: Pirates of the Caribbean: Dead Man's Chest, Reżyser: Gore Verbinski, Budżet: 225000000.0
 - Tytuł: Pirates of the Caribbean: On Stranger Tides, Reżyser: Rob Marshall, Budżet: 250000000.0
 - Tytuł: Pirates of the Caribbean: The Curse of the Black Pearl, Reżyser: Gore Verbinski, Budżet: 140000000.0
----------------
The Host

### Łączenie danych tabelarycznych (concatenate)
funkcja concat() - domyślnie względem wierszy

pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
          keys=None, levels=None, names=None, verify_integrity=False,
          copy=True)

In [83]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'C': ['C0', 'C1', 'C2', 'C3'],
                     'D': ['D0', 'D1', 'D2', 'D3']},
                     index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                     'B': ['B4', 'B5', 'B6', 'B7'],
                     'C': ['C4', 'C5', 'C6', 'C7'],
                     'D': ['D4', 'D5', 'D6', 'D7']},
                      index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                     'B': ['B8', 'B9', 'B10', 'B11'],
                     'C': ['C8', 'C9', 'C10', 'C11'],
                     'D': ['D8', 'D9', 'D10', 'D11']},
                     index=[8, 9, 10, 11])

frame = [df1, df2, df3]

In [84]:
pd.concat(frame)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [85]:
df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                  'D': ['D2', 'D3', 'D6', 'D7'],
                  'F': ['F2', 'F3', 'F6', 'F7']},
                 index=[2, 3, 6, 7])

In [86]:
pd.concat([df1, df4], axis=1)   # łączenie ze wskazaniem pozycji w tabeli

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [87]:
pd.concat([df1, df4], axis=1, join='inner')

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

Funkcja merge() - względem kolumn, indeksów
merge(right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False)

In [88]:
 left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                      'A': ['A0', 'A1', 'A2', 'A3'],
                      'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                       'C': ['C0', 'C1', 'C2', 'C3'],
                       'D': ['D0', 'D1', 'D2', 'D3']})

In [89]:
# kluczowy argument to how który określa sposób łącznie danych, mamy warianty:
#left,           right, outer, inner
pd.merge(left, right, on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3